### ISSUE TITLE
Sprawdzenie zgodności bazy 000webhost z wymaganiami Prestashop

### ISSUE THREAD

**Issue by OrionFOTL** [Information-Systems-Engineering/SuperShop#11]

**Comment by Preatorian** [comment]
000webhost has an inode usage quota limit, that our extracted file structure is exceeding.
Other similar hostings have another issues, involving maximum file size of 15 MB, insufficient for the "prestashop" archive.
So we will be using the [https://freewha.com](https://freewha.com) hosting, which perfectly fits into our needs.
