### ISSUE TITLE
Spróbować wrzucić domyslną instalację Prestashop na 000webhost

### ISSUE THREAD

**Issue by OrionFOTL** [Information-Systems-Engineering/SuperShop#12]
Instalacja z repo po #6

**Comment by Preatorian** [comment]
Just like I've mentioned it in the issue #11, we'll be using now the [https://freewha.com](https://freewha.com) hosting.

Link to our deployed shop: [http://jusshop.freevar.com/shop](http://jusshop.freevar.com/shop)

Any additional usage information will soon appear in the [wiki](../wiki) section.
