### ISSUE TITLE
Uruchomić Prestashop na serwerze i przeprowadzić podstawową konfigurację

### ISSUE THREAD

**Issue by OrionFOTL** [Information-Systems-Engineering/SuperShop#14]

**Comment by OrionFOTL** [comment]
@ushaesel uruchomi na serwerze Mateusza #25

**Comment by ushaesel** [comment]
Sklep jest już postawiony. Tutaj macie wszystkie potrzebne dane:

http://wordpress1909379.home.pl/jusshop/
http://wordpress1909379.home.pl/jusshop/admin28379cus5/
admin jusshop
wsi2019@o2.pl
jebacus123

Jeśli ktoś by chciał jakieś inne loginy i hasła typu ftp/baza/panel home.pl to proszę pisać.
