### ISSUE TITLE
Udostępnić serwer

### ISSUE THREAD

**Issue by OrionFOTL** [Information-Systems-Engineering/SuperShop#25]
Adres IP, dostep do FTP, do bazy itp

**Comment by Demogrogron** [comment]
Serwer : 
https://panel.home.pl
L: wsi2019@o2.pl
H: U4QdnE2O
--------------------------
Dostęp do maila :
L: wsi2019@o2.pl
H: isi2019wsi

**Comment by MadTiger2409** [comment]
Jest git. Wszystko działa 👍
