### ISSUE TITLE
Set protection on master branch to enforce pull requests

### ISSUE THREAD

**Issue by OrionFOTL** [Information-Systems-Engineering/SuperShop#3]

**Comment by MadTiger2409** [comment]
Someone who is not an admin or owner (so @MadTiger2409  and @OrionFOTL can't test it) need to test if he/she is able to commit to the `master` branch.

**Comment by OrionFOTL** [comment]
@Preatorian or @TRUSTMEIMJEDI or @Demogrogron, would you test if you're able to commit directly to `master` please (just add some whitespace or text to Readme and try to push to origin/master)

**Comment by MKA01** [comment]
Nie mam mozliwości wypychania zmian do mastera. Mogę jedynie utworzyć gałąź.

**Comment by OrionFOTL** [comment]
Dzięx
