### ISSUE TITLE
Uzupełnić dane do przelewu, dane o dostawie i zwrotach

### ISSUE THREAD

**Issue by OrionFOTL** [Information-Systems-Engineering/SuperShop#30]
![obraz.png](https://images.zenhubusercontent.com/5dadf99108e469000173220f/075b2dac-f1bc-41c6-962a-dcfd84da1ef8)
![obraz.png](https://images.zenhubusercontent.com/5dadf99108e469000173220f/d107031e-eb93-4c93-b538-e7552ebfed6e)

**Comment by OrionFOTL** [comment]
Oprócz tego wywalić metodę płatności czekiem ze sklepu

**Comment by przempiorkowski** [comment]
![image](https://user-images.githubusercontent.com/47882807/69743652-128c0700-113f-11ea-8ec2-008549648dc2.png)

dodałem zasady dostawy oraz zwrotu

![image](https://user-images.githubusercontent.com/47882807/69743825-60a10a80-113f-11ea-961f-7ab38410556b.png)

usunąłem płatność czekiem 

![image](https://user-images.githubusercontent.com/47882807/69743909-84645080-113f-11ea-95c0-8fb902477fae.png)

dodałem dane przelewu... PS uwaga jest mój numer konta i to nie fake xD

**Comment by OrionFOTL** [comment]
XD
