### ISSUE TITLE
Research publishing Prestashop to Azure

### ISSUE THREAD

**Issue by OrionFOTL** [Information-Systems-Engineering/SuperShop#7]
Find out how to put Prestashop on Azure.
- Can we work on Prestashop locally, configure it, add products and stuff, then put it on Azure?
- Or do we have to do everything on Azure from the start? Install on Azure, configure on Azure?

**Comment by OrionFOTL** [comment]
Helpful Azure marketplace thing: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/prestashop.kickstart?tab=Overview

**Comment by Preatorian** [comment]
Deployment on azure is not possible using our "azure for students" subscription.

![image](https://user-images.githubusercontent.com/28990410/67425519-6fdce780-f5d8-11e9-8392-46f9d1fd9df6.png)

**Comment by OrionFOTL** [comment]
Thanks, let's continue with 000webhost #12 #11
