### ISSUE TITLE
Brainstorm general theme of the store (what to sell)

### ISSUE THREAD

**Issue by OrionFOTL** [Information-Systems-Engineering/SuperShop#8]
* What kind of products will the store sell?
* How to divide the products into categories?

**Comment by MKA01** [comment]
- Tematyką sklepu mogą być zwierzaki domowe. Otworzylibyśmy sklep zoologiczny dla małych pupilów. Sprzedawalibyśmy podstawowe wyposażenie dla hodowców. Posiadalibyśmy produkty takie jak legowiska, klatki, jedzenie, smakołyki, zabawki, witaminy, miski.

- Bardzo prosty podział na psy, koty, ptaki, ryby, gryzonie. Dla każdej kategori moglibyśmy utworzyć podkategorie, przykład: małe/duże/egzotyczne ptaki. Do wyżej wymienionych produktów przypisywalibyśmy kategorie, przykład: klatka dla ptaków egzotycznych będzie również dostępna w kategorii dla dużych ptaków.

**Comment by osmolapatryk** [comment]
1. Sklep z odzieżą dla mężczyzn i dla kobiet.
2. Podział na dwie główne kategorie: ON i ONA a następnie względem części garderoby
-koszulki
-bluzy 
-spodnie
-buty 
-kurtki 
-akcesoria (czapki, biżuteria, dodatki itp.)

**Comment by ushaesel** [comment]
Sklep z częściami komputerowymi:
-podział sprzętu ze względu na kilku producentów (np. Asus, MSI, Intel, AMD)
-podział sprzętu ze względu na jego typ (procek, grafika, dyski, zasilanie itd.)
Coś na wzór takiego xkoma albo moreli z zaznaczeniem tego, że same części a nie gotowych kompów czy innych urządzeń.

**Comment by OrionFOTL** [comment]
Wybieramy odzież 🧺👕
